In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report
from sklearn.neighbors import NearestNeighbors
import folium

In [4]:
df=pd.read_csv('/content/Dataset .csv')

In [5]:
print(df)

      Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City
1           6304287          Izakaya Kikufuji           162       Makati City
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City
3           6318506                      Ooma           162  Mandaluyong City
4           6314302               Sambo Kojin           162  Mandaluyong City
...             ...                       ...           ...               ...
9546        5915730               Naml۱ Gurme           208         ��stanbul
9547        5908749              Ceviz A��ac۱           208         ��stanbul
9548        5915807                     Huqqa           208         ��stanbul
9549        5916112               A���k Kahve           208         ��stanbul
9550        5927402  Walter's Coffee Roastery           208         ��stanbul

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3     Third Floor, Mega Fashion Hall, SM Megamall, O...
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...
...                                                 ...
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                    Karak�_y
9547                                   Ko��uyolu
9548                                 Kuru�_e��me
9549                                 Kuru�_e��me
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green
...                   ...         ...               ...           ...
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
0      Excellent   314
1      Excellent   591
2      Very Good   270
3      Excellent   365
4      Excellent   229
...          ...   ...
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[9551 rows x 21 columns]

In [6]:
print(df.head())

   Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City
1        6304287        Izakaya Kikufuji           162       Makati City
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City
3        6318506                    Ooma           162  Mandaluyong City
4        6314302             Sambo Kojin           162  Mandaluyong City

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3  Third Floor, Mega Fashion Hall, SM Megamall, O...
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...

                                     Locality  \
0   Century City Mall, Poblacion, Makati City
1  Little Tokyo, Legaspi Village, Makati City
2  Edsa Shangri-La, Ortigas, Mandaluyong City
3      SM Megamall, Ortigas, Mandaluyong City
4      SM Megamall, Ortigas, Mandaluyong City

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes
1                          Japanese  ...  Botswana Pula(P)               Yes
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes
3                   Japanese, Sushi  ...  Botswana Pula(P)                No
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3
1                  No                No                   No           3
2                  No                No                   No           4
3                  No                No                   No           4
4                  No                No                   No           4

   Aggregate rating  Rating color Rating text Votes
0               4.8    Dark Green   Excellent   314
1               4.5    Dark Green   Excellent   591
2               4.4         Green   Very Good   270
3               4.9    Dark Green   Excellent   365
4               4.8    Dark Green   Excellent   229

[5 rows x 21 columns]

In [7]:
print(df.tail())

      Restaurant ID           Restaurant Name  Country Code       City  \
9546        5915730               Naml۱ Gurme           208  ��stanbul
9547        5908749              Ceviz A��ac۱           208  ��stanbul
9548        5915807                     Huqqa           208  ��stanbul
9549        5916112               A���k Kahve           208  ��stanbul
9550        5927402  Walter's Coffee Roastery           208  ��stanbul

                                                Address     Locality  \
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...     Karak�_y
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...    Ko��uyolu
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...  Kuru�_e��me
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...  Kuru�_e��me
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...         Moda

            Locality Verbose  Longitude   Latitude  \
9546     Karak�_y, ��stanbul  28.977392  41.022793
9547    Ko��uyolu, ��stanbul  29.041297  41.009847
9548  Kuru�_e��me, ��stanbul  29.034640  41.055817
9549  Kuru�_e��me, ��stanbul  29.036019  41.057979
9550         Moda, ��stanbul  29.026016  40.984776

                             Cuisines  ...          Currency  \
9546                          Turkish  ...  Turkish Lira(TL)
9547  World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548           Italian, World Cuisine  ...  Turkish Lira(TL)
9549                  Restaurant Cafe  ...  Turkish Lira(TL)
9550                             Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[5 rows x 21 columns]

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB
None

In [ ]:
# Display basic information
print(df.head())
print(df.info())

# Handle missing values
df.dropna(subset=['Cuisines', 'Price range'], inplace=True)

# Encode target variable (Cuisine classification)
label_encoder = LabelEncoder()
df['Cuisines'] = label_encoder.fit_transform(df['Cuisines'])

# Separate features and target
X = df.drop(columns=['Cuisines'])
y = df['Cuisines']

# Identify categorical and numerical columns
categorical_columns = X.select_dtypes(include=['object']).columns
numerical_columns = X.select_dtypes(include=['int64', 'float64']).columns

# One-hot encode categorical features
column_transformer = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_columns),
        ('num', StandardScaler(), numerical_columns)
    ]
)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply transformations
X_train = column_transformer.fit_transform(X_train)
X_test = column_transformer.transform(X_test)

# Train classification models
log_reg = LogisticRegression(max_iter=200)
log_reg.fit(X_train, y_train)

rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)

# Evaluate models
y_pred_log_reg = log_reg.predict(X_test)
y_pred_rf = rf_clf.predict(X_test)

print("Logistic Regression Metrics:")
print(classification_report(y_test, y_pred_log_reg))

print("Random Forest Metrics:")
print(classification_report(y_test, y_pred_rf))

   Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City
1        6304287        Izakaya Kikufuji           162       Makati City
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City
3        6318506                    Ooma           162  Mandaluyong City
4        6314302             Sambo Kojin           162  Mandaluyong City

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3  Third Floor, Mega Fashion Hall, SM Megamall, O...
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...

                                     Locality  \
0   Century City Mall, Poblacion, Makati City
1  Little Tokyo, Legaspi Village, Makati City
2  Edsa Shangri-La, Ortigas, Mandaluyong City
3      SM Megamall, Ortigas, Mandaluyong City
4      SM Megamall, Ortigas, Mandaluyong City

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450

   Cuisines  ...          Currency Has Table booking Has Online delivery  \
0       920  ...  Botswana Pula(P)               Yes                  No
1      1111  ...  Botswana Pula(P)               Yes                  No
2      1671  ...  Botswana Pula(P)               Yes                  No
3      1126  ...  Botswana Pula(P)                No                  No
4      1122  ...  Botswana Pula(P)               Yes                  No

  Is delivering now Switch to order menu Price range  Aggregate rating  \
0                No                   No           3               4.8
1                No                   No           3               4.5
2                No                   No           4               4.4
3                No                   No           4               4.9
4                No                   No           4               4.8

   Rating color Rating text Votes
0    Dark Green   Excellent   314
1    Dark Green   Excellent   591
2         Green   Very Good   270
3    Dark Green   Excellent   365
4    Dark Green   Excellent   229

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9542 non-null   int64
 1   Restaurant Name       9542 non-null   object
 2   Country Code          9542 non-null   int64
 3   City                  9542 non-null   object
 4   Address               9542 non-null   object
 5   Locality              9542 non-null   object
 6   Locality Verbose      9542 non-null   object
 7   Longitude             9542 non-null   float64
 8   Latitude              9542 non-null   float64
 9   Cuisines              9542 non-null   int64
 10  Average Cost for two  9542 non-null   int64
 11  Currency              9542 non-null   object
 12  Has Table booking     9542 non-null   object
 13  Has Online delivery   9542 non-null   object
 14  Is delivering now     9542 non-null   object
 15  Switch to order menu  9542 non-null   object
 16  Price range           9542 non-null   int64
 17  Aggregate rating      9542 non-null   float64
 18  Rating color          9542 non-null   object
 19  Rating text           9542 non-null   object
 20  Votes                 9542 non-null   int64
dtypes: float64(3), int64(6), object(12)
memory usage: 1.6+ MB
None